### ISSUE TITLE
Auto Incrementing Primary Keys

### ISSUE THREAD

**Issue by webaction** [specialtactics/l5-api#30]
I'm sure I am doing this right.
I have a model that I want to extend a RestfulModel but use a primary key of id with auto incrementing unsigned int.

`
public $primaryKey = 'id';
public $incrementing = true;
protected $keyType = 'int';
`

**Comment by specialtactics** [comment]
That's generally correct. Are you having any issues?

I don't recommend this be done for 99% for models, but it is useful if you have something like logging where you expect a ton of records, and which do not generally need to be accessed individually through the API.

**Comment by ramizpolic** [comment]
Model-by-ID is not working, mainly because it is automatically converting and switching fields to UUID, as shown here
https://github.com/specialtactics/l5-api/blob/d3f54b6d07a7f47c5760c00e2404e640a10e1280/src/Models/RestfulModel.php#L112-L119

This should be replaced and redefined as either something simple such as:
```php
protected useId = false;

if ($uuidKeyName && !useId && ! is_array($uuidKeyName) && ! array_key_exists($uuidKeyName, $model->getAttributes())) {
    $model->$uuidKeyName = Uuid::uuid4()->toString();
}

```

**Comment by specialtactics** [comment]
Hi @fhivemind, can you please explain what your issue is? Are you trying to use vanilla auto-increment keys, and if so, did you do as is outlined in the OP?

**Comment by ramizpolic** [comment]
Hi @specialtactics , my issue is that due to the creation logic defined for RestfulModel, the ID field is never going to be used. For example, when creating a new object, its ID (as specified in creation logic), is always going to be set up to UUID.

For example,
```php
class Model extends RestfulModel
{
    public $primaryKey = 'id';
    public $incrementing = true;
    protected $keyType = 'int';
    protected $fillable = ['name'];
}
```
and when you try to create a new object via
```php
    Model::create([
        'name' => 'Hello'
    ]);
```

this will fail with 
```
(SQL: insert into "model" ("name", "id") values (Hello, a347810d-8644-476e-a251-50b2a506e419) returning "id")
```

**Comment by specialtactics** [comment]
@fhivemind Okey, I think I understand the problem.

Generally speaking in this situation, I would advise you to actually extend the normal eloquent model rather than the restful model, because you wouldn't be using the functionality anyway.

I can foresee a situation where you might want to use relevant eager loading of item/collection with though - is that the case?

If so I think we can solve this by checking the existing attribute of incrementing rather than creating new redundant attributes. But meanwhile I would recommend that former solution (extend default eloquent model).

I'll keep this open and do the above soon.

**Comment by ramizpolic** [comment]
Yes, the reason to go with the restful model is because of the eager loading and utilizing the restful controllers. I checked the model, and the only problem is creation logic, so let's open a PR with incrementing check. I completely forgot about this attribute 😄
